/*
 * VisualBuildStateMachine Creator
 * Copyright (C) 2026 Yaroslav Donchenko, Yevhenii Donchenko
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 */
#include "dynamicwifitranslator.h"
#include "diagramitem.h"
#include "connect.h"
#include "transitiongroup.h"
#include <QTextStream>
#include <QRegularExpression>
#include <algorithm>
#include "bridgeitem.h"
#include "backitem.h"
#include "groupitem.h"
#include "historyitem.h"
#include "commentitem.h"


DynamicWifiTranslator::DynamicWifiTranslator(QObject *parent) : QObject(parent) {}

DynamicResult DynamicWifiTranslator::generate(QGraphicsScene *scene, const QString &manualHeader, const QString &ssid, const QString &pass)
{
    DynamicResult result;
    QMap<QString, VariableInfo> globalVars;

    // ==========================================
    // 1. СБОР БЛОКОВ
    // ==========================================
    struct BlockData {
        DiagramItem* item;
        int id;
        QString cleanOnEnter;
        QString cleanOnExit;
    };

    QList<BlockData> blocks;
    QList<DiagramItem*> startBlocks;

    for (QGraphicsItem *item : scene->items()) {
        if (DiagramItem *b = dynamic_cast<DiagramItem*>(item)) {
            if (b->getType() == "Стартовый блок" || b->getType() == "Start Block") {
                startBlocks.append(b);
            } else {
                blocks.append({b, 0, "", ""});
            }
        }
    }

    if (startBlocks.isEmpty()) {
        result.error = QObject::tr("ERROR: Start block is missing!");
        return result;
    }

    for (DiagramItem* sb : startBlocks) {
        blocks.prepend({sb, 0, "", ""});
    }

    bool isMulti = (startBlocks.size() > 1);
    int maxTokens = isMulti ? startBlocks.size() : 1;

    // ==========================================
    // 2. НУМЕРАЦИЯ ID И ОЧИСТКА
    // ==========================================
    int idCounter = 1;
    QMap<DiagramItem*, int> blockIdMap;

    for (int i = 0; i < blocks.size(); ++i) {
        blocks[i].id = idCounter++;
        blockIdMap[blocks[i].item] = blocks[i].id;

        // ВАЖНО: Сохраняем в карту для дебаггера
        result.idMap.insert(blocks[i].id, blocks[i].item);

        QString rawEnter = sanitizeForArduino(blocks[i].item->getOnEnter(), false);
        QString rawExit = sanitizeForArduino(blocks[i].item->getOnExit(), false);

        blocks[i].cleanOnEnter = extractVariables(rawEnter, globalVars);
        blocks[i].cleanOnExit = extractVariables(rawExit, globalVars);
    }


    // ==========================================
            // --- АНАЛИЗ ИСТОРИИ (HISTORY) ---
            // ==========================================
            QMap<int, QString> blockToHistoryVar;
            QMap<DiagramItem*, QString> historyTargetVar;

            for (QGraphicsItem *item : scene->items()) {
                if (GroupItem *g = dynamic_cast<GroupItem*>(item)) {
                    HistoryItem* hist = nullptr;
                    for (QGraphicsItem* child : scene->items()) {
                        if (HistoryItem* h = dynamic_cast<HistoryItem*>(child)) {
                            if (g->sceneBoundingRect().contains(h->sceneBoundingRect().center())) {
                                hist = h; break;
                            }
                        }
                    }
                    if (hist) {
                        QString varName = "hist_group_" + QString::number(hist->id());
                        historyTargetVar[hist] = varName;

                        for (DiagramItem* b : blockIdMap.keys()) {
                            if (g->sceneBoundingRect().contains(b->sceneBoundingRect().center()) && b != hist) {
                                blockToHistoryVar[blockIdMap[b]] = varName;
                            }
                        }
                    }
                }
            }

        // --- УМНЫЙ ПАРСИНГ USER HEADER (Отделяем библиотеки от переменных класса) ---
        QStringList headerLines = manualHeader.split('\n');
        QString includesCode, membersCode;
        for (const QString& line : headerLines) {
            if (line.trimmed().startsWith("#include") || line.trimmed().startsWith("#define")) {
                includesCode += line + "\n";
            } else {
                membersCode += line + "\n";
            }
        }

        // ==========================================
        // 3. ГЕНЕРАЦИЯ КОДА (.INO МОНОЛИТ)
        // ==========================================
        QString code;
        QTextStream out(&code);

        out << "// --- DYNAMIC DEBUG FIRMWARE (Wi-Fi TCP/IP - Class Mode) ---\n";
        out << "// Generated by VisioLite for Hardware Debugging\n\n";

        out << "#if defined(ESP32)\n";
        out << "  #include <WiFi.h>\n";
        out << "#elif defined(ESP8266)\n";
        out << "  #include <ESP8266WiFi.h>\n";
        out << "#else\n";
        out << "  #include <WiFi.h> // Fallback\n";
        out << "#endif\n\n";

        if (!includesCode.isEmpty()) {
            out << "// --- User Libraries ---\n" << includesCode << "\n";
        }

        out << "const char* WIFI_SSID = \"" << ssid << "\";\n";
        out << "const char* WIFI_PASS = \"" << pass << "\";\n\n";

        out << "// --- Flags ---\n";
        out << "#define FLAG_ENTER (1u << 0)\n";
        out << "#define FLAG_EXIT  (1u << 1)\n\n";

        out << "class StateMachine;\n";
        out << "typedef void (StateMachine::*StateFunc)(int tokenIdx);\n\n";



        out << "typedef struct {\n";
                out << "    StateFunc     current;\n";
                out << "    StateFunc     nextState;\n";
                out << "    StateFunc     previousState;\n";
                for (auto it = historyTargetVar.begin(); it != historyTargetVar.end(); ++it) {
                    out << "    StateFunc     " << it.value() << ";\n";
                }
                out << "    uint8_t       flags;\n";
                out << "    unsigned long stateStartTime;\n";
                out << "} FSM;\n\n";


        out << "class StateMachine {\n";
        out << "public:\n";
        if (!membersCode.isEmpty()) {
            out << "    // --- User Variables & Methods ---\n";
            out << membersCode << "\n";
        }

        out << "    StateMachine();\n";
        out << "    void setup();\n";
        out << "    void loop();\n";

        out << "\nprivate:\n";
        out << "    FSM activeFSMs[" << maxTokens << "];\n";
        out << "    int activeCount;\n";
        out << "    bool isRunning;\n";
        out << "    WiFiServer* server;\n";
        out << "    WiFiClient client;\n\n";

        out << "    void FSM_Init();\n";
        out << "    void FSM_Tick();\n";
        out << "    void requestTransition(int i, StateFunc target);\n";
        out << "    void dbg_sig(char type, int id);\n\n";

        out << "    // Variables extracted from blocks\n";
        for (auto it = globalVars.begin(); it != globalVars.end(); ++it) {
             out << "    " << it.value().type << " " << it.value().name << ";\n";
        }

        out << "\n    // State Prototypes\n";
        for (const auto& block : blocks) {
            if (dynamic_cast<BackItem*>(block.item) || dynamic_cast<HistoryItem*>(block.item)) continue;
            out << "    void state_" << block.id << "_func(int i);\n";
        }
        out << "};\n\n";

        // --- IMPLEMENTATION ---
        out << "StateMachine::StateMachine() {\n";
        out << "    server = new WiFiServer(8080);\n";
        out << "    activeCount = " << maxTokens << ";\n";
        out << "    isRunning = true;\n";
        for (auto it = globalVars.begin(); it != globalVars.end(); ++it) {
            QString init = it.value().initValue;
            if (!init.isEmpty()) {
                if(init.trimmed().startsWith("=")) init = init.trimmed().mid(1);
                out << "    " << it.value().name << " = " << init << ";\n";
            }
        }
        out << "}\n\n";

        out << "void StateMachine::setup() {\n";
        out << "    Serial.begin(115200);\n";
        out << "    WiFi.begin(WIFI_SSID, WIFI_PASS);\n";
        out << "    \n";
        out << "    // We are waiting endlessly to connect to the router\n";
        out << "    while (WiFi.status() != WL_CONNECTED) delay(500);\n";
        out << "    server->begin();\n";
        out << "    Serial.println(\"--- DEBUG SESSION STARTED ---\");\n";
        out << "    Serial.print(\"IP: \"); Serial.println(WiFi.localIP());\n";
        out << "    \n";
        out << "    // Wait for TCP Client (VisioLite IDE)\n";
        out << "    while (!client || !client.connected()) {\n";
        out << "        client = server->available();\n";
        out << "        delay(10);\n";
        out << "    }\n";
        out << "    FSM_Init();\n";
        out << "}\n\n";

        out << "void StateMachine::dbg_sig(char type, int id) {\n";
        out << "    if (client && client.connected() && client.availableForWrite() >= 16) {\n";
        out << "        client.print(\"[\"); client.print(type); client.print(\":\");\n";
        out << "        client.print(id); client.println(\"]\");\n";
        out << "    }\n";
        out << "}\n\n";

        out << "void StateMachine::loop() {\n";
        out << "    // Восстанавливаем связь, если IDE переподключилась на лету\n";
        out << "    if (!client || !client.connected()) {\n";
        out << "        WiFiClient newClient = server->available();\n";
        out << "        if (newClient) client = newClient;\n";
        out << "    }\n";
        out << "    if (isRunning) FSM_Tick();\n";
        out << "}\n\n";

        out << "void StateMachine::requestTransition(int i, StateFunc target) {\n";
        out << "    activeFSMs[i].nextState = target;\n";
        out << "    activeFSMs[i].flags |= FLAG_EXIT;\n";
        out << "}\n\n";

        out << "void StateMachine::FSM_Init() {\n";
                for (int i = 0; i < maxTokens; ++i) {
                    out << "    activeFSMs[" << i << "].current = &StateMachine::state_" << blockIdMap[isMulti ? startBlocks[i] : startBlocks.first()] << "_func;\n";
                    out << "    activeFSMs[" << i << "].flags = FLAG_ENTER;\n";
                    for (auto it = historyTargetVar.begin(); it != historyTargetVar.end(); ++it) {
                        out << "    activeFSMs[" << i << "]." << it.value() << " = nullptr;\n";
                    }
                }
                out << "}\n\n";

        out << "void StateMachine::FSM_Tick() {\n";
        out << "    for(int i = 0; i < activeCount; i++) {\n";
        out << "        if (activeFSMs[i].current == nullptr) continue;\n\n";
        out << "        if (activeFSMs[i].flags & FLAG_EXIT) {\n";
        out << "            if (activeFSMs[i].current != activeFSMs[i].nextState) {\n";
        out << "            (this->*(activeFSMs[i].current))(i);\n";
        out << "            }\n";
        out << "            activeFSMs[i].previousState = activeFSMs[i].current;\n";
        out << "            activeFSMs[i].current = activeFSMs[i].nextState;\n";
        out << "            if (activeFSMs[i].current != nullptr) activeFSMs[i].flags = FLAG_ENTER;\n";
        out << "            else activeFSMs[i].flags = 0;\n";
        out << "        } else {\n";
        out << "            (this->*(activeFSMs[i].current))(i);\n";
        out << "        }\n";
        out << "    }\n";
        out << "}\n\n";

        int arrowIdCounter = 1000;

        for (const auto& block : blocks) {
            if (dynamic_cast<BackItem*>(block.item) || dynamic_cast<HistoryItem*>(block.item)) continue;

            out << "// ==========================================\n";
            out << "// State ID: " << block.id << "\n";
            out << "void StateMachine::state_" << block.id << "_func(int i) {\n";


            // --- ON ENTER ---
                        out << "    if (activeFSMs[i].flags & FLAG_ENTER) {\n";
                        if (blockToHistoryVar.contains(block.id)) {
                            out << "        activeFSMs[i]." << blockToHistoryVar[block.id] << " = &StateMachine::state_" << block.id << "_func; // Update History\n";
                        }


            if (block.item->data(ROLE_DEBUG_ENABLED).toBool()) {
                out << "        dbg_sig('B', " << block.id << ");\n";
            }
            QString comments = CommentItem::getAssociatedCode(block.item, "// ");
            if (!comments.isEmpty()) out << "        " << comments.replace("\n", "\n        ");
            if (!block.cleanOnEnter.isEmpty()) out << "        " << QString(block.cleanOnEnter).replace("\n", "\n        ") << "\n";

            out << "        activeFSMs[i].stateStartTime = millis();\n";
            out << "        activeFSMs[i].flags &= ~FLAG_ENTER;\n";
            out << "        return;\n";
            out << "    }\n\n";

            // --- ON EXIT ---
            out << "    if (activeFSMs[i].flags & FLAG_EXIT) {\n";
            if (!block.cleanOnExit.isEmpty()) out << "        " << QString(block.cleanOnExit).replace("\n", "\n        ") << "\n";
            out << "        return;\n";
            out << "    }\n\n";

            // --- TRANSITIONS ---
            if (BridgeItem* bridge = dynamic_cast<BridgeItem*>(block.item)) {
                QString targetName = bridge->targetName().trimmed();
                int targetId = -1;
                QString searchName = targetName.startsWith("_") ? targetName.mid(1) : targetName;
                for (auto it = blockIdMap.begin(); it != blockIdMap.end(); ++it) {
                    QString blockLabel = it.key()->getLabel().trimmed();
                    QString cleanLabel = blockLabel.startsWith("_") ? blockLabel.mid(1) : blockLabel;
                    if (cleanLabel.compare(searchName, Qt::CaseInsensitive) == 0) { targetId = it.value(); break; }
                }
                if (targetId != -1) {
                    out << "    // Bridge jump to: " << targetName << "\n";
                    if (block.item->data(ROLE_DEBUG_ENABLED).toBool()) out << "    dbg_sig('C', " << block.id << ");\n";
                    out << "    requestTransition(i, &StateMachine::state_" << targetId << "_func);\n";
                } else {
                    out << "    if (client && client.connected()) client.println(\"Error: Bridge target not found!\");\n";
                    out << "    requestTransition(i, nullptr);\n";
                }
                out << "    return;\n";
                out << "}\n\n";
                continue;
            }

            QList<ConnectionItem*> transitions;
            for (QGraphicsItem *item : scene->items()) {
                 if (item->data(ConnectionRole).toBool()) {
                     ConnectionItem *conn = dynamic_cast<ConnectionItem*>(item);
                     if (conn && conn->startBlock() == block.item && conn->endBlock()) transitions.append(conn);
                 }
            }
            std::sort(transitions.begin(), transitions.end(), [](ConnectionItem *a, ConnectionItem *b) {
                int p1 = (a->transition()) ? a->transition()->getPriority() : 999;
                int p2 = (b->transition()) ? b->transition()->getPriority() : 999;
                return p1 < p2;
            });

            bool hasUncond = false;
            for (ConnectionItem *conn : transitions) {
                int arrowId = arrowIdCounter++;
                result.idMap.insert(arrowId, conn);

                QString cond = sanitizeForArduino(conn->transition()->conditionText(), true).trimmed();
                if (cond.toLower() == "if") cond = "";
                if (cond.toLower().startsWith("if ")) cond = cond.mid(3).trimmed();

                QString actRaw = conn->transition()->actionText().trimmed();
                QString act = (actRaw.toLower() == "action") ? "" : extractVariables(sanitizeForArduino(actRaw, false), globalVars);

                QString targetFunc = "&StateMachine::state_" + QString::number(blockIdMap[conn->endBlock()]) + "_func";


                if (BackItem* back = dynamic_cast<BackItem*>(conn->endBlock())) {
                                    if (back->backMode() != BackItem::Back) {
                                        int targetId = block.id; // Fallback
                                        QString tName = back->targetName();
                                        for (auto it = blockIdMap.begin(); it != blockIdMap.end(); ++it) {
                                            if (it.key()->getLabel() == tName || it.key()->getDescription() == tName) {
                                                targetId = it.value(); break;
                                            }
                                        }
                                        targetFunc = "&StateMachine::state_" + QString::number(targetId) + "_func";
                                    } else {
                                        targetFunc = "activeFSMs[i].previousState";
                                    }
                                } else if (HistoryItem* hist = dynamic_cast<HistoryItem*>(conn->endBlock())) {
                                    if (historyTargetVar.contains(hist)) {
                                        QString varName = historyTargetVar[hist];
                                        int defaultTargetId = 0;
                                        for (QGraphicsItem *ci : scene->items()) {
                                            if (ConnectionItem *c = dynamic_cast<ConnectionItem*>(ci)) {
                                                if (c->startBlock() == hist && c->endBlock() && !c->isBlocked()) {
                                                    defaultTargetId = blockIdMap[c->endBlock()]; break;
                                                }
                                            }
                                        }
                                        if (defaultTargetId != 0) {
                                            targetFunc = "(activeFSMs[i]." + varName + " != nullptr) ? activeFSMs[i]." + varName + " : &StateMachine::state_" + QString::number(defaultTargetId) + "_func";
                                        } else {
                                            targetFunc = "activeFSMs[i]." + varName;
                                        }
                                    }
                                }


                bool isTrue = (cond.isEmpty() || cond == "true" || cond == "1");

                if (isTrue) {
                    if (conn->data(ROLE_DEBUG_ENABLED).toBool()) out << "    dbg_sig('T', " << arrowId << ");\n";
                    if (!act.isEmpty()) out << "    " << act << "\n";
                    out << "    requestTransition(i, " << targetFunc << ");\n";
                    out << "    return;\n";
                    hasUncond = true;
                    break;
                } else {
                    out << "    if (" << cond << ") {\n";
                    if (conn->data(ROLE_DEBUG_ENABLED).toBool()) out << "        dbg_sig('T', " << arrowId << ");\n";
                    if (!act.isEmpty()) out << "        " << act.replace("\n", "\n        ") << "\n";
                    out << "        requestTransition(i, " << targetFunc << ");\n";
                    out << "        return;\n";
                    out << "    } else {\n";
                    if (conn->data(ROLE_DEBUG_ENABLED).toBool()) out << "        dbg_sig('F', " << arrowId << ");\n";
                    out << "    }\n";
                }
            }

            if (!hasUncond && transitions.isEmpty()) {
                 out << "    if (client && client.connected()) client.println(\"Finished.\");\n";
                 out << "    requestTransition(i, nullptr);\n";
            }
            out << "}\n\n";
        }

        // --- MAIN (Global instances) ---
        out << "StateMachine logic;\n\n";
        out << "void setup() {\n";
        out << "    logic.setup();\n";
        out << "}\n\n";
        out << "void loop() {\n";
        out << "    logic.loop();\n";
        out << "}\n";

        result.code = code;
        return result;
    }





// === Утилиты ===
QString DynamicWifiTranslator::sanitizeForArduino(const QString &rawCode, bool isCondition) {
    QString code = rawCode.trimmed();

    // Защита от синтаксических ошибок в метках/экшенах
    if (code.endsWith(":")) code.chop(1);
    if (code.endsWith(":;")) code.chop(2);

    // Заменяем log на Serial.println
    code.replace(QRegularExpression("log\\s*\\((.*)\\)"), "Serial.println(\\1)");
    // string -> String (для удобства Arduino)
    code.replace("std::to_string", "String");
    code.replace("std::string", "String");
    code.replace("string", "String");

    if (!isCondition && !code.isEmpty() && !code.endsWith(';') && !code.endsWith('}')) {
        code += ";";
    }
    return code;
}

QString DynamicWifiTranslator::extractVariables(const QString &rawCode, QMap<QString, VariableInfo> &vars) {
    QString code = rawCode;
    QRegularExpression varRegex(R"(\b(int|float|double|bool|String|char|long|unsigned)\s+(\w+)(\s*=[^;]+)?\s*;)");

    QRegularExpressionMatchIterator i = varRegex.globalMatch(code);
    while (i.hasNext()) {
        QRegularExpressionMatch match = i.next();
        QString full = match.captured(0);
        QString type = match.captured(1);
        QString name = match.captured(2);
        QString val = match.captured(3);

        if (!vars.contains(name)) {
            vars.insert(name, {type, name, val});
        }

        if (!val.isEmpty()) {
            code.replace(full, name + " " + val + ";");
        } else {
            code.replace(full, "");
        }
    }
    return code;
}
